"""Added weight

Revision ID: 4609df18adca
Revises: fc862b31f7ef
Create Date: 2017-01-22 14:29:08.922950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4609df18adca'
down_revision = 'fc862b31f7ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_terms', sa.Column('weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_terms', 'weight')
    # ### end Alembic commands ###
