"""Initial creation

Revision ID: fc862b31f7ef
Revises: 
Create Date: 2017-01-22 12:46:21.477361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc862b31f7ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publication_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('date_published', sa.Date(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('publication_url', sa.String(length=255), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['publication_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SimiliarPublications',
    sa.Column('left_id', sa.Integer(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['left_id'], ['publication.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['publication.id'], ),
    sa.PrimaryKeyConstraint('left_id', 'right_id')
    )
    op.create_table('search_terms',
    sa.Column('pub_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('occurs', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pub_id'], ['publication.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['search_term.id'], ),
    sa.PrimaryKeyConstraint('pub_id', 'term_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_terms')
    op.drop_table('SimiliarPublications')
    op.drop_table('publication')
    op.drop_table('search_term')
    op.drop_table('publication_type')
    # ### end Alembic commands ###
